import type {
  Cliente, Equipamento, Inspecao, Laudo,
  Medicao, Anomalia, DispositivoSeguranca, ChecklistItem, Lead,
} from "./types"

export const CHECKS_PADRAO: ChecklistItem[] = [
  { id: "ck_item_1", secao: "Identificação", item: "Placa de identificação indelével", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_2", secao: "Identificação", item: "Adesivo auxiliar com categoria NR-13", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_3", secao: "Identificação", item: "Número de série confere com documentação", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_4", secao: "Documentação", item: "Prontuário do vaso disponível", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_5", secao: "Documentação", item: "Relatório de inspeção anterior", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_6", secao: "Documentação", item: "Certificados de calibração válidos", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_7", secao: "Instalação", item: "Ambiente limpo e sem obstruções", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_8", secao: "Instalação", item: "Saídas de emergência desobstruídas", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_9", secao: "Instalação", item: "Ventilação adequada", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_10", secao: "Exame Externo", item: "Fundações e estruturas íntegras", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_11", secao: "Exame Externo", item: "Pintura e revestimento em bom estado", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_12", secao: "Exame Externo", item: "Aterramento elétrico adequado", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_13", secao: "Exame Externo", item: "Sem corrosão externa significativa", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_14", secao: "Exame Externo", item: "Suportes e fixações sem deformações", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_15", secao: "Equipamentos", item: "Manômetros com faixa adequada", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_16", secao: "Equipamentos", item: "Válvula de segurança com lacre intacto", ok: true, naoAplicavel: false, observacao: "" },
  { id: "ck_item_17", secao: "Equipamentos", item: "Visor de nível sem vazamentos", ok: true, naoAplicavel: true, observacao: "" },
  { id: "ck_item_18", secao: "Segurança", item: "Procedimentos operacionais disponíveis", ok: true, naoAplicavel: true, observacao: "" },
  { id: "ck_item_19", secao: "Segurança", item: "EPIs disponíveis", ok: true, naoAplicavel: true, observacao: "" },
  { id: "ck_item_20", secao: "Segurança", item: "Válvulas de bloqueio em bom estado", ok: true, naoAplicavel: true, observacao: "" },
  { id: "ck_item_21", secao: "Exame Interno", item: "Acesso interno seguro", ok: null, naoAplicavel: false, observacao: "Não verificado" },
  { id: "ck_item_22", secao: "Exame Interno", item: "Sem trincas ou deformações internas", ok: null, naoAplicavel: false, observacao: "Não verificado" },
  { id: "ck_item_23", secao: "Exame Interno", item: "Sem corrosão interna significativa", ok: null, naoAplicavel: false, observacao: "Não verificado" },
  { id: "ck_item_24", secao: "Teste Hidrostático", item: "Pressão de teste conforme calculada", ok: null, naoAplicavel: false, observacao: "N/A" },
  { id: "ck_item_25", secao: "Teste Hidrostático", item: "Sem vazamentos durante o teste", ok: null, naoAplicavel: false, observacao: "N/A" },
]

export const seedClientes: Cliente[] = [
  {
    id: "c1",
    userId: "user_demo_001",
    nome: "PetroVale Indústria Ltda.",
    cnpj: "12.345.678/0001-90",
    contato: "João Oliveira",
    email: "joao@petrovale.com.br",
    telefone: "(11) 3456-7890",
    endereco: "Av. Industrial, 1500 - São Paulo, SP",
    createdAt: "2024-01-10",
  },
  {
    id: "c2",
    userId: "user_demo_001",
    nome: "Química Nacional S.A.",
    cnpj: "98.765.432/0001-10",
    contato: "Maria Souza",
    email: "maria@quimicanacional.com",
    telefone: "(21) 9876-5432",
    endereco: "Rua dos Químicos, 500 - Rio de Janeiro, RJ",
    createdAt: "2024-02-05",
  },
  {
    id: "c3",
    userId: "user_demo_001",
    nome: "Aços Forte Metalurgia",
    cnpj: "55.123.456/0001-88",
    contato: "Carlos Silva",
    email: "carlos@acosforte.com.br",
    telefone: "(31) 2345-6789",
    endereco: "Rodovia BR-262, km 15 - Contagem, MG",
    createdAt: "2024-03-20",
  },
  {
    id: "c4",
    userId: "user_demo_001",
    nome: "Alimentos Santa Clara Ltda.",
    cnpj: "45.678.901/0001-23",
    contato: "Ana Rodrigues",
    email: "ana@santaclara.com.br",
    telefone: "(41) 3333-4455",
    endereco: "Rua das Indústrias, 800 - Curitiba, PR",
    createdAt: "2024-04-15",
  },
  {
    id: "c5",
    userId: "user_demo_001",
    nome: "Cervejaria do Vale S.A.",
    cnpj: "78.901.234/0001-56",
    contato: "Pedro Henrique Martins",
    email: "pedro@cervejariadovale.com.br",
    telefone: "(51) 3222-1122",
    endereco: "Estrada da Cerveja, 300 - Novo Hamburgo, RS",
    createdAt: "2024-05-01",
  },
  {
    id: "c6",
    userId: "user_demo_001",
    nome: "Usina de Açúcar DoceRio",
    cnpj: "34.567.890/0001-78",
    contato: "Fernando Costa",
    email: "fernando@docerio.com.br",
    telefone: "(16) 3344-5566",
    endereco: "Rodovia SP-310, km 240 - Ribeirão Preto, SP",
    createdAt: "2024-06-01",
  },
]

export const seedEquipamentos: Equipamento[] = [
  // ── PetroVale Indústria (c1) - 4 equipamentos ──
  {
    id: "eq1",
    userId: "user_demo_001",
    clienteId: "c1",
    tag: "V-101",
    descricao: "Reservatório de Ar Comprimido",
    fabricante: "VasosTech",
    numeroSerie: "VT-2021-001",
    anoFabricacao: 2021,
    pressaoOperacao: 1200,
    unidadePressao: "kPa",
    volume: 5,
    pmta: 1500,
    fluido: "Ar Comprimido",
    classeFluido: "C",
    categoria: "IV",
    grupoPotencialRisco: 4,
    pressaoProjeto: 1960,
    pressaoTesteHidrostatico: 2450,
    temperaturaProjeto: 80,
    temperaturaOperacao: 45,
    diametroInterno: 1200,
    alturaComprimento: 2500,
    materialConstrucao: "Aço Carbono",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Compressores - Prédio 1",
    tipo: "vaso",
    createdAt: "2024-01-15",
  },
  {
    id: "eq2",
    userId: "user_demo_001",
    clienteId: "c1",
    tag: "V-102",
    descricao: "Separador de Gás Natural",
    fabricante: "PressCorp",
    numeroSerie: "PC-2020-045",
    anoFabricacao: 2020,
    pressaoOperacao: 3500,
    unidadePressao: "kPa",
    volume: 12,
    pmta: 4200,
    fluido: "Gás Natural",
    classeFluido: "A",
    categoria: "I",
    grupoPotencialRisco: 1,
    pressaoProjeto: 4200,
    pressaoTesteHidrostatico: 5250,
    temperaturaProjeto: 120,
    temperaturaOperacao: 70,
    diametroInterno: 800,
    alturaComprimento: 3000,
    materialConstrucao: "Aço Inoxidável 316L",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Área de Processo - Skid 2",
    tipo: "vaso",
    createdAt: "2024-02-20",
  },
  {
    id: "eq6",
    userId: "user_demo_001",
    clienteId: "c1",
    tag: "V-105",
    descricao: "Filtro de Gás Natural",
    fabricante: "PressCorp",
    numeroSerie: "PC-2023-112",
    anoFabricacao: 2023,
    pressaoOperacao: 2800,
    unidadePressao: "kPa",
    volume: 2,
    pmta: 3500,
    fluido: "Gás Natural",
    classeFluido: "A",
    categoria: "II",
    grupoPotencialRisco: 2,
    pressaoProjeto: 3500,
    pressaoTesteHidrostatico: 4375,
    temperaturaProjeto: 100,
    temperaturaOperacao: 55,
    diametroInterno: 500,
    alturaComprimento: 1800,
    materialConstrucao: "Aço Carbono",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Área de Processo - Skid 2",
    tipo: "vaso",
    createdAt: "2024-05-10",
  },
  {
    id: "eq7",
    userId: "user_demo_001",
    clienteId: "c1",
    tag: "CAL-101",
    descricao: "Caldeira de Recuperação",
    fabricante: "CaldeirasABC",
    numeroSerie: "ABC-2022-050",
    anoFabricacao: 2022,
    pressaoOperacao: 1800,
    unidadePressao: "kPa",
    volume: 45,
    pmta: 2200,
    fluido: "Vapor d'Água",
    classeFluido: "C",
    categoria: "B",
    grupoPotencialRisco: null,
    pressaoProjeto: 2200,
    pressaoTesteHidrostatico: 2750,
    temperaturaProjeto: 250,
    temperaturaOperacao: 200,
    diametroInterno: 2000,
    alturaComprimento: 5000,
    materialConstrucao: "Aço Carbono",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Casa de Caldeiras - Prédio 2",
    tipo: "caldeira",
    createdAt: "2024-06-15",
  },

  // ── Química Nacional (c2) - 4 equipamentos ──
  {
    id: "eq3",
    userId: "user_demo_001",
    clienteId: "c2",
    tag: "V-103",
    descricao: "Tanque de Óleo Térmico",
    fabricante: "TanquesBR",
    numeroSerie: "TBR-2022-012",
    anoFabricacao: 2022,
    pressaoOperacao: 600,
    unidadePressao: "kPa",
    volume: 25,
    pmta: 800,
    fluido: "Óleo Térmico",
    classeFluido: "B",
    categoria: "III",
    grupoPotencialRisco: 3,
    pressaoProjeto: 800,
    pressaoTesteHidrostatico: 1000,
    temperaturaProjeto: 250,
    temperaturaOperacao: 180,
    diametroInterno: 1500,
    alturaComprimento: 3500,
    materialConstrucao: "Aço Carbono",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Setor Térmico - Bloco A",
    tipo: "vaso",
    createdAt: "2024-03-10",
  },
  {
    id: "eq4",
    userId: "user_demo_001",
    clienteId: "c2",
    tag: "CAL-201",
    descricao: "Caldeira Flamotubular",
    fabricante: "CaldeirasABC",
    numeroSerie: "ABC-2019-100",
    anoFabricacao: 2019,
    pressaoOperacao: 1200,
    unidadePressao: "kPa",
    volume: 30,
    pmta: 1500,
    fluido: "Vapor d'Água",
    classeFluido: "C",
    categoria: "B",
    grupoPotencialRisco: null,
    pressaoProjeto: 1500,
    pressaoTesteHidrostatico: 1875,
    temperaturaProjeto: 200,
    temperaturaOperacao: 160,
    diametroInterno: 1000,
    alturaComprimento: 4000,
    materialConstrucao: "Aço Carbono",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Casa de Caldeiras - Bloco B",
    tipo: "caldeira",
    createdAt: "2024-01-05",
  },
  {
    id: "eq8",
    userId: "user_demo_001",
    clienteId: "c2",
    tag: "R-201",
    descricao: "Reator Químico de Síntese",
    fabricante: "ReatoresBRA",
    numeroSerie: "RB-2021-033",
    anoFabricacao: 2021,
    pressaoOperacao: 2500,
    unidadePressao: "kPa",
    volume: 8,
    pmta: 3200,
    fluido: "Compostos Orgânicos",
    classeFluido: "A",
    categoria: "I",
    grupoPotencialRisco: 1,
    pressaoProjeto: 3200,
    pressaoTesteHidrostatico: 4000,
    temperaturaProjeto: 180,
    temperaturaOperacao: 120,
    diametroInterno: 900,
    alturaComprimento: 2800,
    materialConstrucao: "Aço Inoxidável 316L",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Reatores - Bloco C",
    tipo: "vaso",
    createdAt: "2024-07-01",
  },
  {
    id: "eq9",
    userId: "user_demo_001",
    clienteId: "c2",
    tag: "T-201",
    descricao: "Tanque Pulmão de Ácido",
    fabricante: "TanquesBR",
    numeroSerie: "TBR-2020-088",
    anoFabricacao: 2020,
    pressaoOperacao: 300,
    unidadePressao: "kPa",
    volume: 60,
    pmta: 500,
    fluido: "Ácido Sulfúrico",
    classeFluido: "D",
    categoria: "V",
    grupoPotencialRisco: 4,
    pressaoProjeto: 500,
    pressaoTesteHidrostatico: 625,
    temperaturaProjeto: 60,
    temperaturaOperacao: 35,
    diametroInterno: 2500,
    alturaComprimento: 4000,
    materialConstrucao: "Aço Carbono c/ Revestimento",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Armazenamento - Tanque 4",
    tipo: "tanque",
    createdAt: "2024-03-15",
  },

  // ── Aços Forte (c3) - 3 equipamentos ──
  {
    id: "eq5",
    userId: "user_demo_001",
    clienteId: "c3",
    tag: "V-104",
    descricao: "Autoclave Industrial",
    fabricante: "SteriPress",
    numeroSerie: "SP-2023-007",
    anoFabricacao: 2023,
    pressaoOperacao: 250,
    unidadePressao: "kPa",
    volume: 3,
    pmta: 350,
    fluido: "Vapor",
    classeFluido: "C",
    categoria: "V",
    grupoPotencialRisco: 5,
    pressaoProjeto: 350,
    pressaoTesteHidrostatico: null,
    temperaturaProjeto: 150,
    temperaturaOperacao: 130,
    diametroInterno: 600,
    alturaComprimento: 1500,
    materialConstrucao: "Aço Inoxidável 304",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Esterilização - Bloco B",
    tipo: "vaso",
    createdAt: "2024-04-01",
  },
  {
    id: "eq10",
    userId: "user_demo_001",
    clienteId: "c3",
    tag: "CAL-301",
    descricao: "Caldeira Aquatubular",
    fabricante: "GeradoresBR",
    numeroSerie: "GBR-2018-200",
    anoFabricacao: 2018,
    pressaoOperacao: 4200,
    unidadePressao: "kPa",
    volume: 55,
    pmta: 5200,
    fluido: "Vapor Superaquecido",
    classeFluido: "C",
    categoria: "A",
    grupoPotencialRisco: null,
    pressaoProjeto: 5200,
    pressaoTesteHidrostatico: 6500,
    temperaturaProjeto: 350,
    temperaturaOperacao: 300,
    diametroInterno: 1800,
    alturaComprimento: 6000,
    materialConstrucao: "Aço Liga",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Central de Utilidades",
    tipo: "caldeira",
    createdAt: "2024-02-10",
  },
  {
    id: "eq11",
    userId: "user_demo_001",
    clienteId: "c3",
    tag: "V-301",
    descricao: "Acumulador de Condensado",
    fabricante: "VasosTech",
    numeroSerie: "VT-2019-156",
    anoFabricacao: 2019,
    pressaoOperacao: 800,
    unidadePressao: "kPa",
    volume: 15,
    pmta: 1100,
    fluido: "Condensado",
    classeFluido: "C",
    categoria: "IV",
    grupoPotencialRisco: 4,
    pressaoProjeto: 1100,
    pressaoTesteHidrostatico: 1375,
    temperaturaProjeto: 120,
    temperaturaOperacao: 80,
    diametroInterno: 1000,
    alturaComprimento: 2200,
    materialConstrucao: "Aço Carbono",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Central de Utilidades",
    tipo: "vaso",
    createdAt: "2024-02-15",
  },

  // ── Alimentos Santa Clara (c4) - 3 equipamentos ──
  {
    id: "eq12",
    userId: "user_demo_001",
    clienteId: "c4",
    tag: "CAL-401",
    descricao: "Caldeira Mista",
    fabricante: "CaldeirasABC",
    numeroSerie: "ABC-2023-210",
    anoFabricacao: 2023,
    pressaoOperacao: 1000,
    unidadePressao: "kPa",
    volume: 20,
    pmta: 1300,
    fluido: "Vapor d'Água",
    classeFluido: "C",
    categoria: "B",
    grupoPotencialRisco: null,
    pressaoProjeto: 1300,
    pressaoTesteHidrostatico: 1625,
    temperaturaProjeto: 200,
    temperaturaOperacao: 160,
    diametroInterno: 1200,
    alturaComprimento: 3500,
    materialConstrucao: "Aço Carbono",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Processamento - Prédio 1",
    tipo: "caldeira",
    createdAt: "2024-05-10",
  },
  {
    id: "eq13",
    userId: "user_demo_001",
    clienteId: "c4",
    tag: "V-401",
    descricao: "Resfriador de Mosto",
    fabricante: "TanquesBR",
    numeroSerie: "TBR-2023-045",
    anoFabricacao: 2023,
    pressaoOperacao: 400,
    unidadePressao: "kPa",
    volume: 10,
    pmta: 600,
    fluido: "Mosto",
    classeFluido: "D",
    categoria: "V",
    grupoPotencialRisco: 4,
    pressaoProjeto: 600,
    pressaoTesteHidrostatico: null,
    temperaturaProjeto: 100,
    temperaturaOperacao: 60,
    diametroInterno: 800,
    alturaComprimento: 2000,
    materialConstrucao: "Aço Inoxidável 304",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Produção - Tanques",
    tipo: "vaso",
    createdAt: "2024-05-15",
  },
  {
    id: "eq14",
    userId: "user_demo_001",
    clienteId: "c4",
    tag: "T-401",
    descricao: "Tanque de Armazenamento de Óleo Vegetal",
    fabricante: "TanquesBR",
    numeroSerie: "TBR-2024-012",
    anoFabricacao: 2024,
    pressaoOperacao: 200,
    unidadePressao: "kPa",
    volume: 80,
    pmta: 350,
    fluido: "Óleo Vegetal",
    classeFluido: "B",
    categoria: "IV",
    grupoPotencialRisco: 4,
    pressaoProjeto: 350,
    pressaoTesteHidrostatico: null,
    temperaturaProjeto: 50,
    temperaturaOperacao: 30,
    diametroInterno: 3000,
    alturaComprimento: 5000,
    materialConstrucao: "Aço Carbono",
    codigoProjeto: "API 650",
    localizacao: "Armazenagem - Tanque 7",
    tipo: "tanque",
    createdAt: "2024-06-20",
  },

  // ── Cervejaria do Vale (c5) - 3 equipamentos ──
  {
    id: "eq15",
    userId: "user_demo_001",
    clienteId: "c5",
    tag: "CAL-501",
    descricao: "Caldeira Flamotubular",
    fabricante: "CaldeirasABC",
    numeroSerie: "ABC-2022-180",
    anoFabricacao: 2022,
    pressaoOperacao: 900,
    unidadePressao: "kPa",
    volume: 18,
    pmta: 1200,
    fluido: "Vapor d'Água",
    classeFluido: "C",
    categoria: "B",
    grupoPotencialRisco: null,
    pressaoProjeto: 1200,
    pressaoTesteHidrostatico: 1500,
    temperaturaProjeto: 200,
    temperaturaOperacao: 160,
    diametroInterno: 1000,
    alturaComprimento: 3500,
    materialConstrucao: "Aço Carbono",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Cervejaria - Utilidades",
    tipo: "caldeira",
    createdAt: "2024-06-01",
  },
  {
    id: "eq16",
    userId: "user_demo_001",
    clienteId: "c5",
    tag: "V-501",
    descricao: "Tanque de Maturação Pressurizado",
    fabricante: "CervejaTec",
    numeroSerie: "CT-2022-031",
    anoFabricacao: 2022,
    pressaoOperacao: 150,
    unidadePressao: "kPa",
    volume: 50,
    pmta: 250,
    fluido: "Cerveja Carbonatada",
    classeFluido: "D",
    categoria: "V",
    grupoPotencialRisco: 5,
    pressaoProjeto: 250,
    pressaoTesteHidrostatico: null,
    temperaturaProjeto: 30,
    temperaturaOperacao: 10,
    diametroInterno: 2000,
    alturaComprimento: 3500,
    materialConstrucao: "Aço Inoxidável 304",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Cervejaria - Maturação",
    tipo: "vaso",
    createdAt: "2024-06-10",
  },
  {
    id: "eq17",
    userId: "user_demo_001",
    clienteId: "c5",
    tag: "V-502",
    descricao: "Filtro de Cerveja",
    fabricante: "CervejaTec",
    numeroSerie: "CT-2023-044",
    anoFabricacao: 2023,
    pressaoOperacao: 300,
    unidadePressao: "kPa",
    volume: 2,
    pmta: 450,
    fluido: "Cerveja Filtrada",
    classeFluido: "D",
    categoria: "V",
    grupoPotencialRisco: 5,
    pressaoProjeto: 450,
    pressaoTesteHidrostatico: null,
    temperaturaProjeto: 50,
    temperaturaOperacao: 25,
    diametroInterno: 400,
    alturaComprimento: 1000,
    materialConstrucao: "Aço Inoxidável 316L",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Cervejaria - Filtração",
    tipo: "vaso",
    createdAt: "2024-07-05",
  },

  // ── Usina DoceRio (c6) - 3 equipamentos ──
  {
    id: "eq18",
    userId: "user_demo_001",
    clienteId: "c6",
    tag: "CAL-601",
    descricao: "Caldeira de Bagaço de Cana",
    fabricante: "GeradoresBR",
    numeroSerie: "GBR-2020-300",
    anoFabricacao: 2020,
    pressaoOperacao: 2500,
    unidadePressao: "kPa",
    volume: 80,
    pmta: 3200,
    fluido: "Vapor Superaquecido",
    classeFluido: "C",
    categoria: "A",
    grupoPotencialRisco: null,
    pressaoProjeto: 3200,
    pressaoTesteHidrostatico: 4000,
    temperaturaProjeto: 350,
    temperaturaOperacao: 310,
    diametroInterno: 2500,
    alturaComprimento: 8000,
    materialConstrucao: "Aço Liga",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Usina - Geração",
    tipo: "caldeira",
    createdAt: "2024-04-01",
  },
  {
    id: "eq19",
    userId: "user_demo_001",
    clienteId: "c6",
    tag: "T-601",
    descricao: "Tanque de Mel Final",
    fabricante: "TanquesBR",
    numeroSerie: "TBR-2020-099",
    anoFabricacao: 2020,
    pressaoOperacao: 100,
    unidadePressao: "kPa",
    volume: 200,
    pmta: 200,
    fluido: "Mel Final",
    classeFluido: "D",
    categoria: "V",
    grupoPotencialRisco: 5,
    pressaoProjeto: 200,
    pressaoTesteHidrostatico: null,
    temperaturaProjeto: 40,
    temperaturaOperacao: 25,
    diametroInterno: 4000,
    alturaComprimento: 6000,
    materialConstrucao: "Aço Carbono",
    codigoProjeto: "API 650",
    localizacao: "Usina - Armazenagem",
    tipo: "tanque",
    createdAt: "2024-04-10",
  },
  {
    id: "eq20",
    userId: "user_demo_001",
    clienteId: "c6",
    tag: "V-601",
    descricao: "Separador de Álcool",
    fabricante: "PressCorp",
    numeroSerie: "PC-2021-078",
    anoFabricacao: 2021,
    pressaoOperacao: 500,
    unidadePressao: "kPa",
    volume: 35,
    pmta: 700,
    fluido: "Etanol Hidratado",
    classeFluido: "A",
    categoria: "II",
    grupoPotencialRisco: 2,
    pressaoProjeto: 700,
    pressaoTesteHidrostatico: 875,
    temperaturaProjeto: 100,
    temperaturaOperacao: 60,
    diametroInterno: 2000,
    alturaComprimento: 4500,
    materialConstrucao: "Aço Inoxidável 304",
    codigoProjeto: "ASME VIII Div.1",
    localizacao: "Usina - Destilação",
    tipo: "vaso",
    createdAt: "2024-04-15",
  },
]

// ── Medições (reutilizáveis entre inspeções) ──
export const seedMedicoes: Record<string, Medicao[]> = {
  "i1": [
    { id: "m1", ponto: "Costado - Seção A", tipoTampo: null, foto: null, espessura: 12.5, espessuraAnterior: 13.1,
  espessuraConstrucao: 15.1,
  tempoOperacao: 11.8, dataMedicao: "2026-06-15", observacao: "Redução de 4.6% - dentro do esperado" },
    { id: "m2", ponto: "Costado - Seção B", tipoTampo: null, foto: null, espessura: 11.8, espessuraAnterior: 12.0,
  espessuraConstrucao: 14.4,
  tempoOperacao: 11.5, dataMedicao: "2026-06-15", observacao: "Redução de 1.7% - normal" },
    { id: "m3", ponto: "Fundo - Região Sul", tipoTampo: null, foto: null, espessura: 14.2, espessuraAnterior: 14.5,
  espessuraConstrucao: 16.9,
  tempoOperacao: 12.3, dataMedicao: "2026-06-15", observacao: "Sem degradação significativa" },
  ],
  "i2": [
    { id: "m4", ponto: "Costado - Seção A", tipoTampo: null, foto: null, espessura: 18.3, espessuraAnterior: 18.5,
  espessuraConstrucao: 21.2,
  tempoOperacao: 13.5, dataMedicao: "2026-07-05", observacao: "Normal" },
    { id: "m5", ponto: "Costado - Seção C", tipoTampo: null, foto: null, espessura: 9.8, espessuraAnterior: 10.2,
  espessuraConstrucao: 12.3,
  tempoOperacao: 10.9, dataMedicao: "2026-07-05", observacao: "Corrosão uniforme - monitorar" },
    { id: "m6", ponto: "Fundo - Região Norte", tipoTampo: null, foto: null, espessura: 15.1, espessuraAnterior: 15.3,
  espessuraConstrucao: 17.9,
  tempoOperacao: 12.5, dataMedicao: "2026-07-05", observacao: "Normal" },
  ],
  "i3": [
    { id: "m7", ponto: "Costado - Seção B", tipoTampo: null, foto: null, espessura: 10.2, espessuraAnterior: null,
  espessuraConstrucao: 12.7,
  tempoOperacao: 11.1, dataMedicao: "2026-08-22", observacao: "Medição inicial" },
  ],
  "i4": [],
  "i5": [
    { id: "m8", ponto: "Costado - Seção A", tipoTampo: null, foto: null, espessura: 8.7, espessuraAnterior: 9.1,
  espessuraConstrucao: 11.1,
  tempoOperacao: 10.6, dataMedicao: "2026-09-10", observacao: "Redução de 4.4% - dentro do esperado" },
    { id: "m9", ponto: "Fundo - Região Sul", tipoTampo: null, foto: null, espessura: 11.3, espessuraAnterior: 11.5,
  espessuraConstrucao: 13.9,
  tempoOperacao: 11.4, dataMedicao: "2026-09-10", observacao: "Normal" },
  ],
  "i6": [],
  "i7": [
    { id: "m10", ponto: "Costado - Seção B", tipoTampo: null, foto: null, espessura: 14.1, espessuraAnterior: 14.3,
  espessuraConstrucao: 16.8,
  tempoOperacao: 12.2, dataMedicao: "2026-10-01", observacao: "Normal" },
    { id: "m11", ponto: "Fundo - Região Norte", tipoTampo: null, foto: null, espessura: 12.8, espessuraAnterior: 12.9,
  espessuraConstrucao: 15.4,
  tempoOperacao: 11.8, dataMedicao: "2026-10-01", observacao: "Normal" },
  ],
  "i8": [],
  "i10": [
    { id: "m12", ponto: "Costado - Seção A", tipoTampo: null, foto: null, espessura: 16.2, espessuraAnterior: 16.5,
  espessuraConstrucao: 19.0,
  tempoOperacao: 12.9, dataMedicao: "2026-10-15", observacao: "Normal" },
    { id: "m13", ponto: "Costado - Seção B", tipoTampo: null, foto: null, espessura: 15.8, espessuraAnterior: 16.0,
  espessuraConstrucao: 18.6,
  tempoOperacao: 12.7, dataMedicao: "2026-10-15", observacao: "Desgaste uniforme" },
    { id: "m14", ponto: "Fundo - Região Sul", tipoTampo: null, foto: null, espessura: 14.5, espessuraAnterior: 14.7,
  espessuraConstrucao: 17.2,
  tempoOperacao: 12.3, dataMedicao: "2026-10-15", observacao: "Normal" },
  ],
  "i11": [],
  "i12": [
    { id: "m15", ponto: "Costado - Seção C", tipoTampo: null, foto: null, espessura: 7.2, espessuraAnterior: null,
  espessuraConstrucao: 9.6,
  tempoOperacao: 10.2, dataMedicao: "2026-11-05", observacao: "Medição inicial" },
    { id: "m16", ponto: "Tampo superior", tipoTampo: null, foto: null, espessura: 8.1, espessuraAnterior: null,
  espessuraConstrucao: 10.5,
  tempoOperacao: 10.4, dataMedicao: "2026-11-05", observacao: "Medição inicial" },
  ],
  "i13": [
    { id: "m17", ponto: "Costado - Seção A", tipoTampo: null, foto: null, espessura: 10.5, espessuraAnterior: 11.0,
  espessuraConstrucao: 13.0,
  tempoOperacao: 11.2, dataMedicao: "2026-11-20", observacao: "Redução de 4.5% - normal" },
    { id: "m18", ponto: "Fundo - Região Norte", tipoTampo: null, foto: null, espessura: 12.3, espessuraAnterior: 12.5,
  espessuraConstrucao: 14.9,
  tempoOperacao: 11.7, dataMedicao: "2026-11-20", observacao: "Normal" },
  ],
}

// ── Anomalias ──
export const seedAnomalias: Record<string, Anomalia[]> = {
  "i1": [
    { id: "a1", descricao: "Corrosão localizada no costado próximo à saída de dreno", gravidade: "media", foto: null, planoAcao: "Realizar reforço estrutural no próximo reparo programado", resolvida: false },
  ],
  "i2": [
    { id: "a2", descricao: "Válvula de alívio com vazamento residual", gravidade: "alta", foto: null, planoAcao: "Substituir válvula de alívio PSV-201", resolvida: true },
    { id: "a3", descricao: "Junta do flange de inspeção apresenta desgaste", gravidade: "media", foto: null, planoAcao: "Substituir junta na próxima parada programada", resolvida: false },
  ],
  "i3": [],
  "i4": [],
  "i5": [
    { id: "a4", descricao: "Trinca superficial no revestimento térmico", gravidade: "baixa", foto: null, planoAcao: "Reparo cosmético no revestimento", resolvida: true },
  ],
  "i6": [],
  "i7": [],
  "i8": [],
  "i10": [
    { id: "a5", descricao: "Válvula de dreno com vazamento", gravidade: "media", foto: null, planoAcao: "Substituir válvula de dreno na próxima parada", resolvida: false },
  ],
  "i11": [],
  "i12": [],
  "i13": [
    { id: "a6", descricao: "Corrosão puntiforme no costado próximo ao visor de nível", gravidade: "baixa", foto: null, planoAcao: "Monitorar evolução", resolvida: false },
  ],
}

// ── Dispositivos de Segurança ──
export const seedDispositivos: Record<string, DispositivoSeguranca[]> = {
  "i1": [
    { id: "d1", tipo: "valvula_seguranca", tag: "PSV-101", fabricante: "Spirax Sarco", modelo: "SCV-25", numeroSerie: "SS-2025-8871", pressaoAbertura: 1650, pressaoVedacao: 1480, conexaoEntrada: "2\" ANSI 150#", conexaoSaida: "3\" ANSI 150#", ultimaCalibracao: "2025-06-10", proximaCalibracao: "2028-06-10", numeroCertificado: "CAL-PSV-2025-101", inspecaoOk: true, observacao: "Válvula calibrada e operante" },
    { id: "d2", tipo: "manometro", tag: "PI-101", fabricante: "Wika", modelo: "232.50", numeroSerie: "WK-2025-4432", ultimaCalibracao: "2025-12-01", proximaCalibracao: "2026-12-01", numeroCertificado: "CAL-MAN-2025-101", inspecaoOk: true, observacao: "Manômetro calibrado" },
    { id: "d3", tipo: "disco_ruptura", tag: "RD-101", inspecaoOk: false, observacao: "Disco apresenta oxidação - substituir" },
  ],
  "i2": [
    { id: "d4", tipo: "valvula_seguranca", tag: "PSV-201", fabricante: "Leser", modelo: "Type 441", numeroSerie: "LS-2024-6543", pressaoAbertura: 4620, pressaoVedacao: 4150, conexaoEntrada: "1.5\" ANSI 300#", conexaoSaida: "2\" ANSI 150#", ultimaCalibracao: "2024-08-15", proximaCalibracao: "2028-08-15", numeroCertificado: "CAL-PSV-2024-201", inspecaoOk: true, observacao: "Operante" },
    { id: "d5", tipo: "manometro", tag: "PI-201", fabricante: "Ashcroft", modelo: "1279", numeroSerie: "AC-2024-3321", ultimaCalibracao: "2025-06-01", proximaCalibracao: "2026-06-01", numeroCertificado: "CAL-MAN-2025-201", inspecaoOk: true, observacao: "Calibrado" },
  ],
  "i3": [
    { id: "d6", tipo: "valvula_seguranca", tag: "PSV-301", inspecaoOk: true, observacao: "Operante" },
    { id: "d7", tipo: "manometro", tag: "PI-301", inspecaoOk: true, observacao: "Calibrado" },
    { id: "d8", tipo: "termometro", tag: "TI-301", inspecaoOk: true, observacao: "Lendo dentro da faixa" },
  ],
  "i4": [],
  "i5": [
    { id: "d9", tipo: "valvula_seguranca", tag: "PSV-401", inspecaoOk: true, observacao: "Válvula nova - operante" },
    { id: "d10", tipo: "manometro", tag: "PI-401", inspecaoOk: false, observacao: "Manômetro com ponteiro travado - substituir" },
  ],
  "i6": [],
  "i7": [
    { id: "d11", tipo: "valvula_seguranca", tag: "PSV-501", inspecaoOk: true, observacao: "Operante" },
    { id: "d12", tipo: "manometro", tag: "PI-501", inspecaoOk: true, observacao: "Calibrado" },
    { id: "d13", tipo: "visor_nivel", tag: "LG-501", inspecaoOk: true, observacao: "Visor limpo e operante" },
  ],
  "i8": [],
  "i10": [
    { id: "d14", tipo: "valvula_seguranca", tag: "PSV-601", inspecaoOk: true, observacao: "Operante" },
    { id: "d15", tipo: "manometro", tag: "PI-601", inspecaoOk: true, observacao: "Calibrado" },
    { id: "d16", tipo: "termometro", tag: "TI-601", inspecaoOk: true, observacao: "Lendo dentro da faixa" },
  ],
  "i11": [],
  "i12": [
    { id: "d17", tipo: "valvula_seguranca", tag: "PSV-501", inspecaoOk: true, observacao: "Válvula calibrada" },
    { id: "d18", tipo: "manometro", tag: "PI-502", inspecaoOk: true, observacao: "Calibrado" },
    { id: "d19", tipo: "visor_nivel", tag: "LG-502", inspecaoOk: true, observacao: "Visor limpo" },
  ],
  "i13": [
    { id: "d20", tipo: "valvula_seguranca", tag: "PSV-301", inspecaoOk: true, observacao: "Operante" },
    { id: "d21", tipo: "manometro", tag: "PI-302", inspecaoOk: false, observacao: "Manômetro com desvio de calibração - substituir" },
  ],
}

// ── Inspeções ──
export const seedInspecoes: Inspecao[] = [
  // PetroVale
  { id: "i1", userId: "user_demo_001", equipamentoId: "eq1", tipo: "periodica", dataInicio: "2026-06-10", dataTermino: "2026-06-15", examesExternos: true, examesInternos: true, testeHidrostatico: false, thVazamentosVisiveis: null, thDeformacao: null, thAprovado: null, thMotivo: "", plhResponsavel: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", temSPIE: false,   checklist: CHECKS_PADRAO,
    parametrosUltrassom: { aparelho: "GE KRAUTKRAMER DMS2", transdutor: "TC560 / 5 MHz", velocidadeSonica: 5920, tecnica: "Pontual A-SCAN", blocoCalibracao: "5,00 / 25,00 mm" },
  medicoes: seedMedicoes["i1"], anomalias: seedAnomalias["i1"], dispositivosSeguranca: seedDispositivos["i1"], parecer: "Equipamento apto para operação. Realizar inspeção externa em 2027 e interna em 2029.", concluida: true, laudoId: "l1" },
  { id: "i2", userId: "user_demo_001", equipamentoId: "eq2", tipo: "periodica", dataInicio: "2026-07-01", dataTermino: "2026-07-05", examesExternos: true, examesInternos: true, testeHidrostatico: false, thVazamentosVisiveis: null, thDeformacao: null, thAprovado: null, thMotivo: "", plhResponsavel: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", temSPIE: true,   checklist: CHECKS_PADRAO,
    parametrosUltrassom: { aparelho: "GE KRAUTKRAMER DMS2", transdutor: "TC560 / 5 MHz", velocidadeSonica: 5920, tecnica: "Pontual A-SCAN", blocoCalibracao: "5,00 / 25,00 mm" },
  medicoes: seedMedicoes["i2"], anomalias: seedAnomalias["i2"], dispositivosSeguranca: seedDispositivos["i2"], parecer: "Equipamento apto. Próxima inspeção externa em 2029 (SPIE).", concluida: true, laudoId: "l2" },
  { id: "i9", userId: "user_demo_001", equipamentoId: "eq2", tipo: "extraordinaria", dataInicio: "2026-07-06", dataTermino: "2026-07-07", examesExternos: true, examesInternos: false, testeHidrostatico: false, thVazamentosVisiveis: null, thDeformacao: null, thAprovado: null, thMotivo: "", plhResponsavel: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", temSPIE: true,   checklist: CHECKS_PADRAO,
    parametrosUltrassom: { aparelho: "GE KRAUTKRAMER DMS2", transdutor: "TC560 / 5 MHz", velocidadeSonica: 5920, tecnica: "Pontual A-SCAN", blocoCalibracao: "5,00 / 25,00 mm" },
  medicoes: [], anomalias: [], dispositivosSeguranca: [], parecer: "Inspeção extraordinária após reparo na válvula de alívio. Equipamento apto.", concluida: true, laudoId: null },

  // Química Nacional
  { id: "i3", userId: "user_demo_001", equipamentoId: "eq4", tipo: "periodica", dataInicio: "2026-08-20", dataTermino: "2026-08-22", examesExternos: true, examesInternos: false, testeHidrostatico: false, thVazamentosVisiveis: null, thDeformacao: null, thAprovado: null, thMotivo: "", plhResponsavel: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", temSPIE: false,   checklist: CHECKS_PADRAO,
    parametrosUltrassom: { aparelho: "GE KRAUTKRAMER DMS2", transdutor: "TC560 / 5 MHz", velocidadeSonica: 5920, tecnica: "Pontual A-SCAN", blocoCalibracao: "5,00 / 25,00 mm" },
  medicoes: seedMedicoes["i3"], anomalias: seedAnomalias["i3"], dispositivosSeguranca: seedDispositivos["i3"], parecer: "Caldeira apta. Próxima inspeção interna em 12 meses.", concluida: true, laudoId: "l3" },
  { id: "i4", userId: "user_demo_001", equipamentoId: "eq3", tipo: "periodica", dataInicio: "2026-09-01", dataTermino: "", examesExternos: true, examesInternos: true, testeHidrostatico: true, thVazamentosVisiveis: null, thDeformacao: null, thAprovado: null, thMotivo: "", plhResponsavel: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", temSPIE: false,   checklist: CHECKS_PADRAO,
    parametrosUltrassom: { aparelho: "GE KRAUTKRAMER DMS2", transdutor: "TC560 / 5 MHz", velocidadeSonica: 5920, tecnica: "Pontual A-SCAN", blocoCalibracao: "5,00 / 25,00 mm" },
  medicoes: seedMedicoes["i4"], anomalias: seedAnomalias["i4"], dispositivosSeguranca: seedDispositivos["i4"], parecer: "", concluida: false, laudoId: null },
  { id: "i5", userId: "user_demo_001", equipamentoId: "eq8", tipo: "periodica", dataInicio: "2026-09-08", dataTermino: "2026-09-10", examesExternos: true, examesInternos: true, testeHidrostatico: false, thVazamentosVisiveis: null, thDeformacao: null, thAprovado: null, thMotivo: "", plhResponsavel: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", temSPIE: true,   checklist: CHECKS_PADRAO,
    parametrosUltrassom: { aparelho: "GE KRAUTKRAMER DMS2", transdutor: "TC560 / 5 MHz", velocidadeSonica: 5920, tecnica: "Pontual A-SCAN", blocoCalibracao: "5,00 / 25,00 mm" },
  medicoes: seedMedicoes["i5"], anomalias: seedAnomalias["i5"], dispositivosSeguranca: seedDispositivos["i5"], parecer: "Equipamento apto. Classe A - Sigilo de inspeção conforme NR-13.", concluida: true, laudoId: "l4" },

  // Aços Forte
  { id: "i6", userId: "user_demo_001", equipamentoId: "eq10", tipo: "vida_remanescente", dataInicio: "2026-09-15", dataTermino: "", examesExternos: true, examesInternos: true, testeHidrostatico: false, thVazamentosVisiveis: null, thDeformacao: null, thAprovado: null, thMotivo: "", plhResponsavel: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", temSPIE: false,   checklist: CHECKS_PADRAO,
    parametrosUltrassom: { aparelho: "GE KRAUTKRAMER DMS2", transdutor: "TC560 / 5 MHz", velocidadeSonica: 5920, tecnica: "Pontual A-SCAN", blocoCalibracao: "5,00 / 25,00 mm" },
  medicoes: seedMedicoes["i6"], anomalias: seedAnomalias["i6"], dispositivosSeguranca: seedDispositivos["i6"], parecer: "", concluida: false, laudoId: null },

  // Alimentos Santa Clara
  { id: "i7", userId: "user_demo_001", equipamentoId: "eq12", tipo: "inicial", dataInicio: "2026-09-28", dataTermino: "2026-10-01", examesExternos: true, examesInternos: true, testeHidrostatico: true, thVazamentosVisiveis: null, thDeformacao: null, thAprovado: null, thMotivo: "", plhResponsavel: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", temSPIE: false,   checklist: CHECKS_PADRAO,
    parametrosUltrassom: { aparelho: "GE KRAUTKRAMER DMS2", transdutor: "TC560 / 5 MHz", velocidadeSonica: 5920, tecnica: "Pontual A-SCAN", blocoCalibracao: "5,00 / 25,00 mm" },
  medicoes: seedMedicoes["i7"], anomalias: seedAnomalias["i7"], dispositivosSeguranca: seedDispositivos["i7"], parecer: "Equipamento novo - apto para operação. Próxima inspeção interna em 24 meses.", concluida: true, laudoId: "l5" },

  // Cervejaria do Vale
  { id: "i8", userId: "user_demo_001", equipamentoId: "eq15", tipo: "periodica", dataInicio: "2026-10-10", dataTermino: "", examesExternos: true, examesInternos: false, testeHidrostatico: false, thVazamentosVisiveis: null, thDeformacao: null, thAprovado: null, thMotivo: "", plhResponsavel: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", temSPIE: false,   checklist: CHECKS_PADRAO,
    parametrosUltrassom: { aparelho: "GE KRAUTKRAMER DMS2", transdutor: "TC560 / 5 MHz", velocidadeSonica: 5920, tecnica: "Pontual A-SCAN", blocoCalibracao: "5,00 / 25,00 mm" },
  medicoes: seedMedicoes["i8"], anomalias: seedAnomalias["i8"], dispositivosSeguranca: seedDispositivos["i8"], parecer: "", concluida: false, laudoId: null },
  { id: "i12", userId: "user_demo_001", equipamentoId: "eq16", tipo: "periodica", dataInicio: "2026-11-03", dataTermino: "2026-11-05", examesExternos: true, examesInternos: true, testeHidrostatico: false, thVazamentosVisiveis: null, thDeformacao: null, thAprovado: null, thMotivo: "", plhResponsavel: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", temSPIE: false,   checklist: CHECKS_PADRAO,
    parametrosUltrassom: { aparelho: "GE KRAUTKRAMER DMS2", transdutor: "TC560 / 5 MHz", velocidadeSonica: 5920, tecnica: "Pontual A-SCAN", blocoCalibracao: "5,00 / 25,00 mm" },
  medicoes: seedMedicoes["i12"], anomalias: seedAnomalias["i12"], dispositivosSeguranca: seedDispositivos["i12"], parecer: "Tanque de maturação apto. Inspeção externa em 2027, interna em 2029.", concluida: true, laudoId: "l7" },

  // Usina DoceRio
  { id: "i10", userId: "user_demo_001", equipamentoId: "eq20", tipo: "periodica", dataInicio: "2026-10-13", dataTermino: "2026-10-15", examesExternos: true, examesInternos: true, testeHidrostatico: false, thVazamentosVisiveis: null, thDeformacao: null, thAprovado: null, thMotivo: "", plhResponsavel: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", temSPIE: true,   checklist: CHECKS_PADRAO,
    parametrosUltrassom: { aparelho: "GE KRAUTKRAMER DMS2", transdutor: "TC560 / 5 MHz", velocidadeSonica: 5920, tecnica: "Pontual A-SCAN", blocoCalibracao: "5,00 / 25,00 mm" },
  medicoes: seedMedicoes["i10"], anomalias: seedAnomalias["i10"], dispositivosSeguranca: seedDispositivos["i10"], parecer: "Separador de álcool apto. Classe A - rigor normativo. Próxima externa em 2030 (SPIE).", concluida: true, laudoId: "l6" },
  { id: "i11", userId: "user_demo_001", equipamentoId: "eq18", tipo: "vida_remanescente", dataInicio: "2026-11-01", dataTermino: "", examesExternos: true, examesInternos: true, testeHidrostatico: false, thVazamentosVisiveis: null, thDeformacao: null, thAprovado: null, thMotivo: "", plhResponsavel: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", temSPIE: false,   checklist: CHECKS_PADRAO,
    parametrosUltrassom: { aparelho: "GE KRAUTKRAMER DMS2", transdutor: "TC560 / 5 MHz", velocidadeSonica: 5920, tecnica: "Pontual A-SCAN", blocoCalibracao: "5,00 / 25,00 mm" },
  medicoes: seedMedicoes["i11"], anomalias: seedAnomalias["i11"], dispositivosSeguranca: seedDispositivos["i11"], parecer: "", concluida: false, laudoId: null },

  // Aços Forte
  { id: "i13", userId: "user_demo_001", equipamentoId: "eq11", tipo: "periodica", dataInicio: "2026-11-18", dataTermino: "2026-11-20", examesExternos: true, examesInternos: true, testeHidrostatico: false, thVazamentosVisiveis: null, thDeformacao: null, thAprovado: null, thMotivo: "", plhResponsavel: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", temSPIE: false,   checklist: CHECKS_PADRAO,
    parametrosUltrassom: { aparelho: "GE KRAUTKRAMER DMS2", transdutor: "TC560 / 5 MHz", velocidadeSonica: 5920, tecnica: "Pontual A-SCAN", blocoCalibracao: "5,00 / 25,00 mm" },
  medicoes: seedMedicoes["i13"], anomalias: seedAnomalias["i13"], dispositivosSeguranca: seedDispositivos["i13"], parecer: "Acumulador de condensado apto. Próxima inspeção externa em 2027, interna em 2029.", concluida: true, laudoId: "l8" },
]

// ── Laudos ──
export const seedLaudos: Laudo[] = [
  { id: "l1", userId: "user_demo_001", inspecaoId: "i1", equipamentoId: "eq1", numeroLaudo: "NR13-LD-2026-0001", dataEmissao: "2026-06-20", plhNome: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", plhAssinatura: null, dataProximaInspecao: "2029-06-15", pdfUrl: null, observacoes: "Laudo referente à inspeção periódica do V-101 - PetroVale Indústria" },
  { id: "l2", userId: "user_demo_001", inspecaoId: "i2", equipamentoId: "eq2", numeroLaudo: "NR13-LD-2026-0002", dataEmissao: "2026-07-10", plhNome: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", plhAssinatura: null, dataProximaInspecao: "2032-07-05", pdfUrl: null, observacoes: "Laudo referente à inspeção periódica do V-102 - PetroVale Indústria (SPIE)" },
  { id: "l3", userId: "user_demo_001", inspecaoId: "i3", equipamentoId: "eq4", numeroLaudo: "NR13-LD-2026-0003", dataEmissao: "2026-08-25", plhNome: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", plhAssinatura: null, dataProximaInspecao: "2027-08-22", pdfUrl: null, observacoes: "Laudo referente à inspeção periódica da CAL-201 - Química Nacional" },
  { id: "l4", userId: "user_demo_001", inspecaoId: "i5", equipamentoId: "eq8", numeroLaudo: "NR13-LD-2026-0004", dataEmissao: "2026-09-15", plhNome: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", plhAssinatura: null, dataProximaInspecao: "2032-09-10", pdfUrl: null, observacoes: "Laudo referente à inspeção periódica do R-201 - Química Nacional (SPIE)" },
  { id: "l5", userId: "user_demo_001", inspecaoId: "i7", equipamentoId: "eq12", numeroLaudo: "NR13-LD-2026-0005", dataEmissao: "2026-10-05", plhNome: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", plhAssinatura: null, dataProximaInspecao: "2028-10-01", pdfUrl: null, observacoes: "Laudo de inspeção inicial da CAL-401 - Alimentos Santa Clara" },
  { id: "l6", userId: "user_demo_001", inspecaoId: "i10", equipamentoId: "eq20", numeroLaudo: "NR13-LD-2026-0006", dataEmissao: "2026-10-20", plhNome: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", plhAssinatura: null, dataProximaInspecao: "2032-10-15", pdfUrl: null, observacoes: "Laudo referente à inspeção periódica do V-601 - Usina DoceRio (SPIE)" },
  { id: "l7", userId: "user_demo_001", inspecaoId: "i12", equipamentoId: "eq16", numeroLaudo: "NR13-LD-2026-0007", dataEmissao: "2026-11-10", plhNome: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", plhAssinatura: null, dataProximaInspecao: "2029-11-05", pdfUrl: null, observacoes: "Laudo de inspeção periódica do V-501 (Tanque de Maturação) - Cervejaria do Vale" },
  { id: "l8", userId: "user_demo_001", inspecaoId: "i13", equipamentoId: "eq11", numeroLaudo: "NR13-LD-2026-0008", dataEmissao: "2026-11-25", plhNome: "Eng. Carlos Alberto Santos", plhCrea: "CREA-SP 123.456", plhAssinatura: null, dataProximaInspecao: "2029-11-20", pdfUrl: null, observacoes: "Laudo de inspeção periódica do V-301 (Acumulador de Condensado) - Aços Forte" },
]

// ── Leads (carteira de possíveis compradores via WhatsApp) ──
export const seedLeads: Lead[] = [
  {
    id: "lead1",
    userId: "nr13pro_empresa",
    nome: "Ricardo Almeida",
    whatsapp: "5511998765432",
    email: "ricardo.almeida@industria.com.br",
    origem: "landing",
    status: "novo",
    mensagemAutomatizada: "Olá Ricardo! Vi que você demonstrou interesse no NR-13 Pro. Posso ajudar com alguma dúvida sobre o fechamento?",
    criadoEm: "2026-07-28T14:30:00Z",
    ultimoContato: null,
    transferidoConsultor: false,
    acessoDegustacaoLiberado: false,
    dataLiberacaoAcesso: null,
    credenciaisDegustacao: null,
  },
  {
    id: "lead2",
    userId: "nr13pro_empresa",
    nome: "Fernanda Lima",
    whatsapp: "5511987654321",
    email: "fernanda.lima@quimica.com.br",
    origem: "checkout",
    status: "abandonou_checkout",
    mensagemAutomatizada: "Olá Fernanda! Notei que você iniciou a assinatura do NR-13 Pro mas não concluiu. Teve alguma dúvida no fechamento? Posso te ajudar!",
    criadoEm: "2026-07-29T10:15:00Z",
    ultimoContato: "2026-07-29T10:20:00Z",
    transferidoConsultor: false,
    acessoDegustacaoLiberado: false,
    dataLiberacaoAcesso: null,
    credenciaisDegustacao: null,
  },
  {
    id: "lead3",
    userId: "nr13pro_empresa",
    nome: "Marcos Vinícius",
    whatsapp: "5511912345678",
    email: "marcos.v@metalurgica.com.br",
    origem: "plataforma",
    status: "contatado",
    mensagemAutomatizada: "Olá Marcos! Obrigado pelo interesse no NR-13 Pro. Posso esclarecer alguma dúvida sobre o plano?",
    criadoEm: "2026-07-25T09:00:00Z",
    ultimoContato: "2026-07-26T15:45:00Z",
    transferidoConsultor: false,
    acessoDegustacaoLiberado: false,
    dataLiberacaoAcesso: null,
    credenciaisDegustacao: null,
  },
  {
    id: "lead4",
    userId: "nr13pro_empresa",
    nome: "Patrícia Gomes",
    whatsapp: "5511987651234",
    email: "patricia.gomes@alimentos.com.br",
    origem: "checkout",
    status: "em_negociacao",
    mensagemAutomatizada: "Olá Patrícia! Vi que você está avaliando o NR-13 Pro. Posso te passar mais detalhes sobre os recursos?",
    criadoEm: "2026-07-22T16:00:00Z",
    ultimoContato: "2026-07-27T11:30:00Z",
    transferidoConsultor: false,
    acessoDegustacaoLiberado: true,
    dataLiberacaoAcesso: "2026-07-27T11:35:00Z",
    credenciaisDegustacao: { email: "patricia.gomes@degustacao.nr13pro.com.br", senha: "123456", expiraEm: "2026-08-03T11:35:00Z" },
  },
  {
    id: "lead5",
    userId: "nr13pro_empresa",
    nome: "Eduardo Santos",
    whatsapp: "5511911112222",
    email: "eduardo.santos@cervejaria.com.br",
    origem: "landing",
    status: "consultor",
    mensagemAutomatizada: "Olá Eduardo! Vou transferir você para um consultor que poderá tirar todas as suas dúvidas. Um momento, por favor!",
    criadoEm: "2026-07-20T13:00:00Z",
    ultimoContato: "2026-07-24T10:00:00Z",
    transferidoConsultor: true,
    acessoDegustacaoLiberado: false,
    dataLiberacaoAcesso: null,
    credenciaisDegustacao: null,
  },
  {
    id: "lead6",
    userId: "nr13pro_empresa",
    nome: "Juliana Castro",
    whatsapp: "5511988887777",
    email: "juliana.castro@usina.com.br",
    origem: "checkout",
    status: "convertido",
    mensagemAutomatizada: "Olá Juliana! Sua assinatura foi confirmada. Bem-vinda ao NR-13 Pro! 🎉",
    criadoEm: "2026-07-18T08:30:00Z",
    ultimoContato: "2026-07-18T09:00:00Z",
    transferidoConsultor: false,
    acessoDegustacaoLiberado: true,
    dataLiberacaoAcesso: "2026-07-18T08:45:00Z",
    credenciaisDegustacao: { email: "juliana.castro@degustacao.nr13pro.com.br", senha: "123456", expiraEm: "2026-07-25T08:45:00Z" },
  },
  {
    id: "lead7",
    userId: "nr13pro_empresa",
    nome: "Roberto Nunes",
    whatsapp: "5511966665555",
    email: "roberto.nunes@petroleo.com.br",
    origem: "landing",
    status: "perdido",
    mensagemAutomatizada: "Olá Roberto! Posso ajudar com alguma dúvida sobre o NR-13 Pro?",
    criadoEm: "2026-07-15T11:00:00Z",
    ultimoContato: "2026-07-16T14:00:00Z",
    transferidoConsultor: false,
    acessoDegustacaoLiberado: false,
    dataLiberacaoAcesso: null,
    credenciaisDegustacao: null,
  },
]
