export { clienteService } from "./cliente-service"
export { equipamentoService } from "./equipamento-service"
export { inspecaoService } from "./inspecao-service"
export { laudoService } from "./laudo-service"
export { settingsService } from "./settings-service"
